services:
    FL\XeroBundle\XeroPHP\ApplicationFactory: ~

    XeroPHP\Application:
        factory: 'FL\XeroBundle\XeroPHP\ApplicationFactory:createApplication'
        arguments: [ "%fl_xero.config%", '@doctrine.orm.entity_manager']
