services:
    FL\XeroBundle\XeroPHP\ApplicationFactory: ~

    XeroPHP\Application:
        factory: 'FL\XeroBundle\XeroPHP\ApplicationFactory:createApplication'
        arguments: ["%fl_xero.type%", "%fl_xero.config%"]
